name: myanmar_calendar_example
description: "Example app demonstrating Myanmar Calendar library usage"
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  myanmar_calendar_widget:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
