name: myanmar_calendar_widget
description: "A comprehensive calendar library for Flutter featuring Myanmar and Hindu (Panchanga) calendar widgets with date conversion, compact and full display modes, and traditional calendar support."
version: 0.1.0
homepage: https://github.com/BlacMeW/myanmar_calendar
repository: https://github.com/BlacMeW/myanmar_calendar
issue_tracker: https://github.com/BlacMeW/myanmar_calendar/issues
documentation: https://github.com/BlacMeW/myanmar_calendar#readme

topics:
  - myanmar
  - hindu
  - calendar
  - date-conversion
  - flutter

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
